server:
  servlet:
    context-path: /api/
  port: 8181
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
